template: v1/cfn/shared/pipelines/simple-pipeline/simple-pipeline.template.yml
stack_name: engine-theme-sdk-inf-pipeline
region: us-east-1

context:
  pipeline:
    name: engine-theme-sdk-inf
    restart_on_update: true

    git:
      owner: WPMedia
      branch: staging
      repo: engine-theme-sdk

    stages:
      - name: Pipeline
        actions:
          - name: RebuildThisPipeline
            config: cfn/configs/deployment.yml

      - name: Package-and-Deploy
        actions:
          - name: Package-and-Deploy
            image: aws/codebuild/standard:2.0
            buildspec: codebuild/buildspec.yml
            outputArtifact: ServerlessPackage
            env_vars:
              phase: Package