name: Canary build

# Controls when the action will run. Triggers the workflow on push
# events but only for the test-canary-branch branch
on:
  push:
    branches:
      - test-canary-build

# Publishes Canary builds with the dist tag of "canary" and
# with a version of 0.0.0 with a short git SHA appended to
# the end.
jobs:
  # This workflow contains a single job called "publish"
  publish:
    name: Canary build publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache NPM files
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PERSONAL_AUTH_TOKEN }}
      
      - run: npm version prerelease --preid=canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
