name: Test Engine Theme SDK

on:
  pull_request:
    # synchronize	commit(s) pushed to the pull request
    types: [synchronize, opened]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.THEMES_OPS_SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node with 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Clean install dependencies if lockfile changed
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests with coverage minimum
        run: npm run test:coverage

      - name: Check linting
        run: npm run lint

      - name: Typescript Compile
        run: npm run build:dts

      - name: Check failure status and post in themes ops channel
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
