name: Test ci

on:
  push:
    branches:
      - CI-fix-npm-ci-fail-on-publish

jobs:
  publish:
    name: ci-fail-on-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Sets up Node v12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - run: npm ci
